version: '3.8'

services:
  # Samuel Bunker Portfolio Website
  sambunker-portfolio:
    build: .
    restart: unless-stopped
    ports:
      - "${INTERNAL_PORT}:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - d-nginx_default
    logging:
      driver: syslog
      options:
        syslog-address: "udp://${LOGGING_IP}:1514"
        tag: "sambunker-portfolio"

networks:
  d-nginx_default:
    external: true
